version: '3.4'

volumes:
  mysql_data:
    driver: local
  public_data:
    driver: local

services:
  app:
    build:
      context: .
    ports:
      - "80:8080"
    volumes:
      - .:/web-security
      - public_data:/var/public
    links:
      - db
    depends_on:
      - db
    environment:
      DB_SERVER: db
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"

  volumeInit:
    image: alpine
    volumes:
      - public_data:/var/public
    command: chown -R nobody:nobody /var/public

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
